# Generated by Django 3.2.1 on 2023-03-15 10:55

import allocationapp.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedToModel',
            fields=[
                ('WWID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BenchAllocationDataModel',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('Program', models.CharField(blank=True, max_length=10)),
                ('SKU', models.CharField(blank=True, max_length=10)),
                ('Vendor', models.CharField(blank=True, max_length=255)),
                ('Who', djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.AllocatedToModel)),
                ('FromWW', models.CharField(blank=True, max_length=20)),
                ('ToWW', models.CharField(blank=True, max_length=20)),
                ('Duration', models.CharField(blank=True, max_length=10, null=True)),
                ('Team', models.CharField(blank=True, max_length=20)),
                ('Remarks', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BenchesModel',
            fields=[
                ('key', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('BenchName', models.CharField(blank=True, max_length=10, null=True)),
                ('IsAllocated', models.BooleanField(default=False)),
                ('IsRequested', models.BooleanField(default=False)),
                ('seatNo', models.CharField(blank=True, max_length=10, null=True)),
                ('seatLabel', models.CharField(blank=True, max_length=10, null=True)),
                ('dir', models.CharField(blank=True, max_length=5, null=True)),
                ('labelNo', models.CharField(blank=True, max_length=5, null=True)),
                ('team', models.CharField(blank=True, max_length=10, null=True)),
                ('AllocationData', djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.BenchAllocationDataModel, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenchesRowModel',
            fields=[
                ('seatRowLabel', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('IsRowSpace', models.BooleanField(default=False)),
                ('seats', djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.BenchesModel, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('NumberOfWorkbenches', models.IntegerField()),
                ('AllocatedWorkbenches', models.IntegerField(default=0)),
                ('BenchDetails', djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.BenchesRowModel, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgramShortName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProgramName', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, unique=True)),
                ('Colourcode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion_by', djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.AllocatedToModel, null=True)),
                ('suggestion', models.TextField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('resolved_date', models.DateTimeField(null=True)),
                ('closing_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRolesModel',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('VendorName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestModel',
            fields=[
                ('RequestId', models.AutoField(primary_key=True, serialize=False)),
                ('WWID', models.PositiveIntegerField(default=0)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Idsid', models.CharField(blank=True, max_length=255, null=True)),
                ('DisplayName', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Badge', models.CharField(blank=True, max_length=2, null=True)),
                ('ApprovedOn', models.DateTimeField()),
                ('CreatedOn', models.DateTimeField()),
                ('ApprovedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('IsAdded', models.BooleanField(default=False)),
                ('IsRequested', models.BooleanField(default=False)),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocationapp.userrolesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('WWID', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Idsid', models.CharField(blank=True, max_length=255, null=True)),
                ('DisplayName', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Badge', models.CharField(blank=True, max_length=2, null=True)),
                ('LastLoggedOn', models.DateTimeField()),
                ('CreatedOn', models.DateTimeField()),
                ('IsActive', models.BooleanField(default=True)),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocationapp.userrolesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SkuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkuName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProgramName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocationapp.programsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationDetailsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Program', models.CharField(blank=True, max_length=100)),
                ('Sku', models.CharField(blank=True, max_length=100)),
                ('Vendor', models.CharField(blank=True, max_length=100)),
                ('Team', models.CharField(blank=True, max_length=100, null=True)),
                ('AllocatedTo', djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.AllocatedToModel, null=True)),
                ('NotifyTo', djongo.models.fields.JSONField(blank=True, null=True)),
                ('FromWW', models.CharField(blank=True, max_length=20)),
                ('ToWW', models.CharField(blank=True, max_length=20)),
                ('Duration', models.CharField(blank=True, max_length=10, null=True)),
                ('NumberOfbenches', models.IntegerField()),
                ('Remarks', models.TextField(blank=True)),
                ('IsAllocated', models.BooleanField(default=False)),
                ('IsRequested', models.BooleanField(default=False)),
                ('BenchData', djongo.models.fields.JSONField(blank=True, null=True)),
                ('DeallocatedBenchData', djongo.models.fields.JSONField(blank=True, null=True)),
                ('AllocatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('Reason', models.CharField(blank=True, max_length=255, null=True)),
                ('Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocationapp.labmodel')),
            ],
        ),
    ]
