# Generated by Django 3.2.1 on 2023-03-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverUserModel',
            fields=[
                ('WWID', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Idsid', models.CharField(blank=True, max_length=255, null=True)),
                ('DisplayName', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Badge', models.CharField(blank=True, max_length=2, null=True)),
                ('LastLoggedOn', models.DateTimeField()),
                ('CreatedOn', models.DateTimeField()),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
    ]
