# Generated by Django 3.2 on 2023-09-27 17:01

from django.db import migrations, models

# def set_deallocated_fields(apps, schema_editor):
#     AllocationDetailsModel = apps.get_model('allocationapp', 'AllocationDetailsModel')
#     for allocation in AllocationDetailsModel.objects.all():
#         allocation.DeallocatedBy = None  # Set the field to None
#         allocation.DeallocatedDate = None  # Set the field to None
#         allocation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0004_auto_20230927_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationdetailsmodel',
            name='DeallocatedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocationdetailsmodel',
            name='DeallocatedDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        # migrations.RunPython(set_deallocated_fields),
    ]
