# Generated by Django 3.2 on 2023-09-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0005_auto_20230927_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationdetailsmodel',
            name='DeallocatedBy',
        ),
        migrations.RemoveField(
            model_name='allocationdetailsmodel',
            name='DeallocatedDate',
        ),
    ]
