# Generated by Django 3.2 on 2023-09-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0006_auto_20230927_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationdetailsmodel',
            name='DeallocatedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allocationdetailsmodel',
            name='DeallocatedDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
