# Generated by Django 3.2 on 2023-09-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0007_auto_20230927_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationdetailsmodel',
            name='DeallocatedBy',
        ),
        migrations.RemoveField(
            model_name='allocationdetailsmodel',
            name='DeallocatedDate',
        ),
    ]
