# Generated by Django 3.2 on 2024-04-16 03:56

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0012_boardallocationdatamodel_boardallocationdatamodeltrackdata_broadcastmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmodel',
            name='DeletedUser',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
