# Generated by Django 3.2 on 2024-05-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0013_broadcastmodel_deleteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmodel',
            name='Location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
