# Generated by Django 3.2 on 2024-06-18 05:11

import allocationapp.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0014_broadcastmodel_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackSelfModel',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('IsAllocated', models.BooleanField(default=False)),
                ('IsRequested', models.BooleanField(default=False)),
                ('labelNo', models.CharField(blank=True, max_length=50, null=True)),
                ('shelfNo', models.CharField(blank=True, max_length=50, null=True)),
                ('AllocationData', djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.BenchAllocationDataModel, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='benchallocationdatamodel',
            name='Department',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='benchallocationdatamodel',
            name='Function',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
