# Generated by Django 3.2 on 2024-06-18 05:15

import allocationapp.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allocationapp', '0015_auto_20240618_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationdetailsmodel',
            name='Department',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allocationdetailsmodel',
            name='Function',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='benchesmodel',
            name='RackDetail',
            field=djongo.models.fields.ArrayField(blank=True, model_container=allocationapp.models.RackSelfModel, null=True),
        ),
        migrations.CreateModel(
            name='FunctionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Function', models.CharField(blank=True, max_length=255, null=True)),
                ('TeamName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocationapp.teamsmodel')),
            ],
        ),
    ]
